package com.tweetapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@DynamoDBTable(tableName = "tweetTable")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Tweet {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String tweet;
	private String postTime;
    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.L)
	private List<Tweet> replies;
    @DynamoDBAttribute
    private User user;
    @DynamoDBAttribute
	private Likes likes;



}
