package com.tweetapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
@DynamoDBTable(tableName = "userTable")
public class User {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	private String id;
    private String firstName;
    private String lastName;
    private String email;
    private String gender;
    private String birthdate;
    private String address;
    private String password;
    private String activeStatus;

}
